//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVSplitter {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSVSplitter.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die close ähnelt.
        /// </summary>
        internal static string button_close {
            get {
                return ResourceManager.GetString("button_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DO THE SPLIT ähnelt.
        /// </summary>
        internal static string button_do_split {
            get {
                return ResourceManager.GetString("button_do_split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add header to split files ähnelt.
        /// </summary>
        internal static string checkbox_add_header_to_split_files {
            get {
                return ResourceManager.GetString("checkbox_add_header_to_split_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source file contains header line ähnelt.
        /// </summary>
        internal static string checkbox_source_has_header {
            get {
                return ResourceManager.GetString("checkbox_source_has_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die write prefix in split files ähnelt.
        /// </summary>
        internal static string checkbox_target_prefix {
            get {
                return ResourceManager.GetString("checkbox_target_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use splitting creteria ähnelt.
        /// </summary>
        internal static string checkbox_use_advanced_options {
            get {
                return ResourceManager.GetString("checkbox_use_advanced_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use column extraction ähnelt.
        /// </summary>
        internal static string checkbox_use_columns {
            get {
                return ResourceManager.GetString("checkbox_use_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The process reported an error. Please check the log file. ähnelt.
        /// </summary>
        internal static string exit_error {
            get {
                return ResourceManager.GetString("exit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The process ended succesfully. ähnelt.
        /// </summary>
        internal static string exit_ok {
            get {
                return ResourceManager.GetString("exit_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Columnoptions ähnelt.
        /// </summary>
        internal static string label_column_options {
            get {
                return ResourceManager.GetString("label_column_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die export columns ähnelt.
        /// </summary>
        internal static string label_export_header {
            get {
                return ResourceManager.GetString("label_export_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSVSplit+ splits CSV files into parts with a defined number of lines.
        ///
        ///This program can be used free of charge, without any warranty.
        ///For more information please visit ähnelt.
        /// </summary>
        internal static string label_info {
            get {
                return ResourceManager.GetString("label_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column delimiter ähnelt.
        /// </summary>
        internal static string label_input_field_delimiter {
            get {
                return ResourceManager.GetString("label_input_field_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line break ähnelt.
        /// </summary>
        internal static string label_input_line_delimiter {
            get {
                return ResourceManager.GetString("label_input_line_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sourceoptions ähnelt.
        /// </summary>
        internal static string label_input_options {
            get {
                return ResourceManager.GetString("label_input_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text delimiter ähnelt.
        /// </summary>
        internal static string label_input_text_delimiter {
            get {
                return ResourceManager.GetString("label_input_text_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input file ähnelt.
        /// </summary>
        internal static string label_inputfile {
            get {
                return ResourceManager.GetString("label_inputfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column delimiter ähnelt.
        /// </summary>
        internal static string label_output_field_delimiter {
            get {
                return ResourceManager.GetString("label_output_field_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line break ähnelt.
        /// </summary>
        internal static string label_output_line_delimiter {
            get {
                return ResourceManager.GetString("label_output_line_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Targetoptions ähnelt.
        /// </summary>
        internal static string label_output_options {
            get {
                return ResourceManager.GetString("label_output_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text delimiter ähnelt.
        /// </summary>
        internal static string label_output_text_delimiter {
            get {
                return ResourceManager.GetString("label_output_text_delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data prefix block ähnelt.
        /// </summary>
        internal static string label_prefix {
            get {
                return ResourceManager.GetString("label_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of prefix lines ähnelt.
        /// </summary>
        internal static string label_source_prefix {
            get {
                return ResourceManager.GetString("label_source_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split after number of lines ähnelt.
        /// </summary>
        internal static string label_split_after {
            get {
                return ResourceManager.GetString("label_split_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split options ähnelt.
        /// </summary>
        internal static string label_split_options {
            get {
                return ResourceManager.GetString("label_split_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        internal static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help ähnelt.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quit ähnelt.
        /// </summary>
        internal static string menu_quit {
            get {
                return ResourceManager.GetString("menu_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die index as column number ähnelt.
        /// </summary>
        internal static string radio_header_indices {
            get {
                return ResourceManager.GetString("radio_header_indices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die index as colum name ähnelt.
        /// </summary>
        internal static string radio_header_names {
            get {
                return ResourceManager.GetString("radio_header_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split after line matching regex below ähnelt.
        /// </summary>
        internal static string radio_split_after {
            get {
                return ResourceManager.GetString("radio_split_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split before line matching regex below ähnelt.
        /// </summary>
        internal static string radio_split_before {
            get {
                return ResourceManager.GetString("radio_split_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon titlebar_icon {
            get {
                object obj = ResourceManager.GetObject("titlebar_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        internal static string window_title_about {
            get {
                return ResourceManager.GetString("window_title_about", resourceCulture);
            }
        }
    }
}
